remote_theme: poole/lanyon

# Setup
title:               UCSB Collaboratory
tagline:             'Working together to close the technological gap'
description:         'This is a page for twitter data and its analysis.'
url:                 'https://ucsb-collaboratory.github.io/twitter/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Amelia Meyer
  url:               ameliameyer.github.io
  email:             ameliameyer@ucsb.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
© 2021 GitHub, Inc.
